name: Installer build

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:
  build-windows-installer:
    name: Build Windows installer
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate Gradle
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jpackage
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./app/build/dist/Xeres-*.exe
        name: windows-installer
        retention-days: 1

  build-linux-installer:
    name: Build Linux installer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate Gradle
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jpackage
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./app/build/dist/xeres_*.deb
        name: linux-installer
        retention-days: 1

  build-macos-installer:
    name: Build MacOS installer
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate Gradle
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jpackage
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./app/build/dist/Xeres-*.dmg
        name: macos-installer
        retention-days: 1

  calculate-hashes:
    name: Calculate hashes
    runs-on: ubuntu-latest
    needs: [ build-windows-installer, build-linux-installer, build-macos-installer ]
    steps:
    - name: Calculate
      uses: MCJack123/ghaction-generate-release-hashes@v3
      with:
        file-name: SHA256SUMS.txt
        get-assets: true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./SHA256SUMS.txt
        name: sha256sums
        retention-days: 1

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [ build-windows-installer, build-linux-installer, build-macos-installer, calculate-hashes ]
    steps:
    - name: Download Windows installer
      uses: actions/download-artifact@v2
      with:
        name: windows-installer
    - name: Download Linux installer
      uses: actions/download-artifact@v2
      with:
        name: linux-installer
    - name: Download MacOS installer
      uses: actions/download-artifact@v2
      with:
        name: macos-installer
    - name: Download SHA256SUMS
      uses: actions/download-artifact@v2
      with:
        name: calculate-hashes
    - name: Create Github release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        files: |
          *.exe
          *.deb
          *.dmg
          SHA256SUMS.txt

# For manual builds, add automatic_release_tag: "Nightly" above
